# Generated by Django 6.0 on 2025-12-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_availability_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
